### ISSUE TITLE
'PytestPluginManager' object has no attribute 'notify_exception'

### ISSUE THREAD

**Issue by msarahan** [pytest-dev/pytest-xdist#175]
Seeing this with recent CI builds, not sure what the cause is.  This happens on both Appveyor and Travis for me.

Appveyor: https://ci.appveyor.com/project/ContinuumAnalyticsFOSS/conda-build/build/1.0.2196/job/h78r7704romkxf7b#L748
Travis: https://travis-ci.org/conda/conda-build/jobs/248131289#L1430

pytest-xdist in use is 1.18.0: https://travis-ci.org/conda/conda-build/jobs/248131289#L902
pytest in use is 3.1.2: https://travis-ci.org/conda/conda-build/jobs/248131289#L898

Any hints much appreciated.

**Comment by nicoddemus** [comment]
Thanks @msarahan for reporting.

Hmmm it seems this is a bug in `pytest-xdist` in [here](https://github.com/pytest-dev/pytest-xdist/blob/master/xdist/slavemanage.py#L326), this should be:

```python
self.config.notify_exception(excinfo)
```

`PytestPluginManager` does not have that method at all. As this happen in an error handler it seems this is just hiding the real exception, the classic case of the error handler giving an error and shadowing the actual exception. 😓 

We definitely should fix this for `1.18.1`.

**Comment by zzzeek** [comment]
I'm on 1.18.1 and getting this error like mad, I can no longer see test failures in my CI.   It doesn't seem like any fix was committed here?

**Comment by RonnyPfannschmidt** [comment]
indeed something went wrong there, i#ll try to take a look at fix*release today

**Comment by nicoddemus** [comment]
>  It doesn't seem like any fix was committed here?

It wasn't, sorry about that.

Opened up a tentative fix at #194.

**Comment by nicoddemus** [comment]
Note: I didn't fix the original problem, at least now `xdist` should be able to print the actual error before crashing down in flames. 🔥

**Comment by nicoddemus** [comment]
`1.18.2` has been released, thanks again for the report
